name: Run Tests

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  echo-command:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Verify where we are at the moment
      run: |
        echo $PWD
        ls

    - name: Run Docker container and echo command
      run: |
        docker pull cordmaur/merge-downloader:v1
        docker-compose -f run_tests.yml run --rm mycontainer
        
        
